name: Manual Build with Vite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci  # ensure package-lock.json is present if using npm ci

      - name: Build production (minified)
        run: npm run build:prod

      - name: Build production (non-minified)
        run: npm run build:dev

      - name: Upload minified artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-prod
          path: dist-prod/

      - name: Upload non-minified artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-dev
          path: dist-dev/