name: Manual Build

# Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build production file
        run: npm run build

      - name: Upload production artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist/
